"""
Unit tests for _build_ast_context() in src/hooks/pre_tool_use.py.

@see EARS-002#REQ-E004
@see EARS-002#REQ-W005
@see EARS-002#REQ-W006
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
import unittest

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(_HERE)
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from src.hooks.pre_tool_use import _build_ast_context  # noqa: E402


def _write_file(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


class TestBuildAstContext(unittest.TestCase):

    def setUp(self) -> None:
        self._tmpdir = tempfile.TemporaryDirectory()
        self.root = self._tmpdir.name

        # Set up a minimal .cartographer_state pointing at output_dir
        self.output_dir = os.path.join(self.root, "output")
        os.makedirs(self.output_dir, exist_ok=True)

        state_path = os.path.join(self.root, ".cartographer_state")
        # Format: "<head_hash> <timestamp> <output_dir>"
        _write_file(state_path, f"abc123 2026-01-01T00:00:00Z {self.output_dir}")

        # Create a dummy source file inside the repo root
        self.src_dir = os.path.join(self.root, "src")
        os.makedirs(self.src_dir, exist_ok=True)
        self.target_file = os.path.join(self.src_dir, "example.py")
        _write_file(self.target_file, "# placeholder\n")

    def tearDown(self) -> None:
        self._tmpdir.cleanup()

    def _write_digest(self, files: list) -> None:
        digest = {
            "generated_at": "2026-01-01T00:00:00Z",
            "head_hash": "abc123",
            "files": files,
        }
        digest_path = os.path.join(self.output_dir, "ast-digest.json")
        _write_file(digest_path, json.dumps(digest))

    # ------------------------------------------------------------------
    # REQ-E004: Returns correct Markdown when entry is present and valid
    # ------------------------------------------------------------------
    def test_returns_markdown_for_matching_entry(self) -> None:
        """_build_ast_context returns a Symbol Digest table when file is found."""
        self._write_digest([
            {
                "path": "src/example.py",
                "parse_status": "ok",
                "symbols": [
                    {"name": "MyClass", "kind": "class", "line_start": 1, "line_end": 50},
                    {"name": "MyClass.method", "kind": "method", "line_start": 10, "line_end": 30},
                    {"name": "helper", "kind": "function", "line_start": 55, "line_end": 60},
                ],
            }
        ])
        result = _build_ast_context(self.target_file)
        self.assertIsNotNone(result)
        self.assertIn("## Symbol Digest: src/example.py", result)
        self.assertIn("| `MyClass` | class | 1–50 |", result)
        self.assertIn("| `MyClass.method` | method | 10–30 |", result)
        self.assertIn("| `helper` | function | 55–60 |", result)
        self.assertIn("_auto generated by git-cartographer_", result)

    # ------------------------------------------------------------------
    # REQ-E004: Returns None when file not in digest
    # ------------------------------------------------------------------
    def test_returns_none_when_file_not_in_digest(self) -> None:
        """_build_ast_context returns None for a file not listed in ast-digest.json."""
        self._write_digest([
            {
                "path": "src/other.py",
                "parse_status": "ok",
                "symbols": [
                    {"name": "Foo", "kind": "class", "line_start": 1, "line_end": 10},
                ],
            }
        ])
        result = _build_ast_context(self.target_file)
        self.assertIsNone(result)

    # ------------------------------------------------------------------
    # REQ-W006: Returns None when parse_status != "ok"
    # ------------------------------------------------------------------
    def test_returns_none_when_parse_status_not_ok(self) -> None:
        """_build_ast_context returns None when parse_status is not 'ok'."""
        for status in ("skipped_language", "skipped_size", "failed"):
            with self.subTest(parse_status=status):
                self._write_digest([
                    {
                        "path": "src/example.py",
                        "parse_status": status,
                        "symbols": [
                            {"name": "Foo", "kind": "class", "line_start": 1, "line_end": 10},
                        ],
                    }
                ])
                result = _build_ast_context(self.target_file)
                self.assertIsNone(result)

    # ------------------------------------------------------------------
    # REQ-W006: Returns None when symbols list is empty
    # ------------------------------------------------------------------
    def test_returns_none_when_symbols_empty(self) -> None:
        """_build_ast_context returns None when symbols list is empty."""
        self._write_digest([
            {
                "path": "src/example.py",
                "parse_status": "ok",
                "symbols": [],
            }
        ])
        result = _build_ast_context(self.target_file)
        self.assertIsNone(result)

    # ------------------------------------------------------------------
    # REQ-W005: Returns None and writes to stderr when ast-digest.json absent
    # ------------------------------------------------------------------
    def test_returns_none_and_warns_when_digest_missing(self) -> None:
        """_build_ast_context returns None and emits a warning when ast-digest.json is absent."""
        # Do NOT write digest file
        import io
        captured = io.StringIO()
        old_stderr = sys.stderr
        sys.stderr = captured
        try:
            result = _build_ast_context(self.target_file)
        finally:
            sys.stderr = old_stderr

        self.assertIsNone(result)
        warning = captured.getvalue()
        self.assertIn("warning: ast-digest.json not found at", warning)
        self.assertIn("symbol resolution disabled", warning)
        self.assertIn("Fix: run cartographer first", warning)


if __name__ == "__main__":
    unittest.main()
